import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { Octokit } from "octokit";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

export async function POST(req: NextRequest) {
  const { code, fileName } = await req.json();

  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4000,
    messages: [{
      role: "user",
      content: `You are a senior code reviewer. Review this file, find all issues, and return the fully fixed version.

File: ${fileName}
\`\`\`
${code}
\`\`\`

Return raw JSON only — no markdown, no backticks:
{
  "score": 85,
  "summary": "2 issues found and fixed",
  "issues": [
    {
      "id": "issue-1",
      "severity": "warning",
      "line": 42,
      "issue": "Unused variable declared but never used",
      "original": "const tempData = fetchData();",
      "fix": "Remove unused variable"
    }
  ],
  "fixed_code": "COMPLETE fixed file content here",
  "diff": [
    { "line": 42, "original": "const tempData = fetchData();", "fixed": "" }
  ]
}`
    }]
  });

  const raw = message.content[0].type === "text" ? message.content[0].text : "";
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) return NextResponse.json({ error: "Parse failed" }, { status: 500 });

  const result = JSON.parse(match[0]);
  return NextResponse.json({ status: "complete", ...result });
}

export async function PUT(req: NextRequest) {
  const { filePath, fixedContent, summary } = await req.json();

  const owner = process.env.GITHUB_OWNER!;
  const repo  = process.env.GITHUB_REPO!;
  const branch = `fix/ai-review-${Date.now()}`;

  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const { data: refData  } = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${repoData.default_branch}` });

  await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: refData.object.sha });

  const { data: fileData } = await octokit.rest.repos.getContent({ owner, repo, path: filePath });

  await octokit.rest.repos.createOrUpdateFileContents({
    owner, repo, path: filePath, branch,
    message: `fix: ${summary}`,
    content: Buffer.from(fixedContent).toString("base64"),
    sha: (fileData as any).sha,
  });

  const { data: pr } = await octokit.rest.pulls.create({
    owner, repo,
    title: `fix: ${summary}`,
    head: branch,
    base: repoData.default_branch,
    body: `## AI Code Review Fix\n\n${summary}\n\n_Auto-generated by AI Agents Dashboard_`,
  });

  return NextResponse.json({ pr_url: pr.html_url, branch });
}