// import { NextRequest, NextResponse } from "next/server";
// import Anthropic from "@anthropic-ai/sdk";
// import { Octokit } from "octokit";

// const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
// const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

// export async function POST(req: NextRequest) {
//   const { code, fileName } = await req.json();

//   const message = await anthropic.messages.create({
//     model: "claude-sonnet-4-20250514",
//     max_tokens: 4000,
//     messages: [{
//       role: "user",
//       content: `You are a senior code reviewer. Review this file, find all issues, and return the fully fixed version.

// File: ${fileName}
// \`\`\`
// ${code}
// \`\`\`

// Return raw JSON only — no markdown, no backticks:
// {
//   "score": 85,
//   "summary": "2 issues found and fixed",
//   "issues": [
//     {
//       "id": "issue-1",
//       "severity": "warning",
//       "line": 42,
//       "issue": "Unused variable declared but never used",
//       "original": "const tempData = fetchData();",
//       "fix": "Remove unused variable"
//     }
//   ],
//   "fixed_code": "COMPLETE fixed file content here",
//   "diff": [
//     { "line": 42, "original": "const tempData = fetchData();", "fixed": "" }
//   ]
// }`
//     }]
//   });

//   const raw = message.content[0].type === "text" ? message.content[0].text : "";
//   const match = raw.match(/\{[\s\S]*\}/);
//   if (!match) return NextResponse.json({ error: "Parse failed" }, { status: 500 });

//   const result = JSON.parse(match[0]);
//   return NextResponse.json({ status: "complete", ...result });
// }

// export async function PUT(req: NextRequest) {
//   const { filePath, fixedContent, summary } = await req.json();

//   const owner = process.env.GITHUB_OWNER!;
//   const repo  = process.env.GITHUB_REPO!;
//   const branch = `fix/ai-review-${Date.now()}`;

//   const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
//   const { data: refData  } = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${repoData.default_branch}` });

//   await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: refData.object.sha });

//   const { data: fileData } = await octokit.rest.repos.getContent({ owner, repo, path: filePath });

//   await octokit.rest.repos.createOrUpdateFileContents({
//     owner, repo, path: filePath, branch,
//     message: `fix: ${summary}`,
//     content: Buffer.from(fixedContent).toString("base64"),
//     sha: (fileData as any).sha,
//   });

//   const { data: pr } = await octokit.rest.pulls.create({
//     owner, repo,
//     title: `fix: ${summary}`,
//     head: branch,
//     base: repoData.default_branch,
//     body: `## AI Code Review Fix\n\n${summary}\n\n_Auto-generated by AI Agents Dashboard_`,
//   });

//   return NextResponse.json({ pr_url: pr.html_url, branch });
// }
import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { Octokit } from "octokit";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const octokit   = new Octokit({ auth: process.env.GITHUB_TOKEN });

// ── Helpers ───────────────────────────────────────────────────────────────────
function buildPrompt(mode: string, content: string, source: string) {
  const modeContext: Record<string, string> = {
    "github-pr":  "You are reviewing a GitHub Pull Request diff.",
    "github-url": "You are reviewing a single file fetched from GitHub.",
    "git-diff":   "You are reviewing a git diff — focus only on the changed lines (+/-).",
    "paste":      "You are reviewing a file pasted by the developer.",
  };
  return `${modeContext[mode] || "You are a senior code reviewer."}

Source: ${source}

Content:
\`\`\`
${content.slice(0, 12000)}
\`\`\`

Find all real bugs, security issues, performance problems, and code quality issues. Be specific — reference actual line numbers and code from the content.

Return ONLY valid JSON — no markdown, no backticks, no explanation:
{
  "score": <number 0-100>,
  "summary": "<one sentence>",
  "passed": <number of checks passed>,
  "issues": [
    {
      "id": "<unique-id>",
      "severity": "<critical|serious|warning|info>",
      "issue": "<specific description — mention the actual code/variable/function>",
      "line": <line number if applicable, else omit>,
      "fix": "<exact fix with explanation>",
      "codePreview": "<actual problematic code snippet>",
      "codeFixed": "<corrected code snippet>"
    }
  ],
  "fixed_code": "<complete corrected file content>"
}`;
}

// ── POST — scan ───────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  const { mode, prUrl, fileUrl, diff, code, filePath } = await req.json();

  try {
    let content = "";
    let sourceLabel = "";

    if (mode === "github-pr") {
      // Extract owner/repo/pr from URL
      const match = prUrl.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
      if (!match) return NextResponse.json({ error: "Invalid GitHub PR URL" }, { status: 400 });
      const [, owner, repo, pull_number] = match;

      const { data: pr } = await octokit.rest.pulls.get({ owner, repo, pull_number: parseInt(pull_number) });
      const { data: files } = await octokit.rest.pulls.listFiles({ owner, repo, pull_number: parseInt(pull_number) });

      sourceLabel = `PR #${pull_number} — ${pr.title}`;
      content = files.map(f => `=== ${f.filename} ===\n${f.patch || "(binary file)"}`).join("\n\n");

    } else if (mode === "github-url") {
      // Convert github.com URL to raw.githubusercontent.com
      const rawUrl = fileUrl
        .replace("github.com", "raw.githubusercontent.com")
        .replace("/blob/", "/");
      const res = await fetch(rawUrl, { headers: { "Authorization": `token ${process.env.GITHUB_TOKEN}` } });
      if (!res.ok) return NextResponse.json({ error: `Could not fetch file: ${res.status}` }, { status: 400 });
      content = await res.text();
      sourceLabel = fileUrl.replace("https://github.com/", "");

    } else if (mode === "git-diff") {
      content = diff;
      sourceLabel = "Git diff";

    } else {
      content = code;
      sourceLabel = filePath || "Pasted file";
    }

    if (!content.trim()) return NextResponse.json({ error: "No content to review" }, { status: 400 });

    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 4000,
      messages: [{ role: "user", content: buildPrompt(mode, content, sourceLabel) }]
    });

    const raw = message.content[0].type === "text" ? message.content[0].text : "";
    const match = raw.match(/\{[\s\S]*\}/);
    if (!match) return NextResponse.json({ error: "Failed to parse AI response" }, { status: 500 });

    const result = JSON.parse(match[0]);
    return NextResponse.json({ status: "complete", sourceLabel, inputMode: mode, ...result });

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

// ── PUT — push PR ─────────────────────────────────────────────────────────────
export async function PUT(req: NextRequest) {
  const { filePath, fixedContent, summary } = await req.json();

  const owner  = process.env.GITHUB_OWNER!;
  const repo   = process.env.GITHUB_REPO!;
  const branch = `fix/ai-review-${Date.now()}`;

  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const { data: refData }  = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${repoData.default_branch}` });

  await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: refData.object.sha });

  const { data: fileData } = await octokit.rest.repos.getContent({ owner, repo, path: filePath });
  await octokit.rest.repos.createOrUpdateFileContents({
    owner, repo, path: filePath, branch,
    message: `fix: ${summary}`,
    content: Buffer.from(fixedContent).toString("base64"),
    sha: (fileData as any).sha,
  });

  const { data: pr } = await octokit.rest.pulls.create({
    owner, repo,
    title: `fix: ${summary}`,
    head: branch,
    base: repoData.default_branch,
    body: `## AI Code Review Fix\n\n${summary}\n\n_Auto-generated by AI Super Agents_`,
  });

  return NextResponse.json({ pr_url: pr.html_url, branch });
}